# Generated by Django 2.1.2 on 2020-04-20 11:16

import datetime
from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default='PM0000', max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ('Aadhar Card', 'Aadhar Card'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License')], max_length=25)),
                ('id_number', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('rating', models.IntegerField(default=1)),
                ('pic', django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
