# Generated by Django 3.0.5 on 2020-05-10 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_base64field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('r10000', models.IntegerField(default=0)),
                ('r5000', models.IntegerField(default=0)),
                ('r2000', models.IntegerField(default=0)),
                ('r1000', models.IntegerField(default=0)),
                ('r500', models.IntegerField(default=0)),
                ('r100', models.IntegerField(default=0)),
                ('r50', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default='PM0000', max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ('Aadhar Card', 'Aadhar Card'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License')], max_length=25)),
                ('id_number', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('rating', models.IntegerField(default=1)),
                ('pic', django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r10000', models.IntegerField(default=0)),
                ('r5000', models.IntegerField(default=0)),
                ('r2000', models.IntegerField(default=0)),
                ('r1000', models.IntegerField(default=0)),
                ('r500', models.IntegerField(default=0)),
                ('r100', models.IntegerField(default=0)),
                ('r50', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=25)),
                ('staff_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('r10000', models.IntegerField(default=0)),
                ('r5000', models.IntegerField(default=0)),
                ('r2000', models.IntegerField(default=0)),
                ('r1000', models.IntegerField(default=0)),
                ('r500', models.IntegerField(default=0)),
                ('r100', models.IntegerField(default=0)),
                ('r50', models.IntegerField(default=0)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Members')),
            ],
        ),
    ]
