# Generated by Django 2.1.2 on 2020-04-20 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('r10000', models.IntegerField(default=0)),
                ('r5000', models.IntegerField(default=0)),
                ('r2000', models.IntegerField(default=0)),
                ('r1000', models.IntegerField(default=0)),
                ('r500', models.IntegerField(default=0)),
                ('r100', models.IntegerField(default=0)),
                ('r50', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemberCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('r10000', models.IntegerField(default=0)),
                ('r5000', models.IntegerField(default=0)),
                ('r2000', models.IntegerField(default=0)),
                ('r1000', models.IntegerField(default=0)),
                ('r500', models.IntegerField(default=0)),
                ('r100', models.IntegerField(default=0)),
                ('r50', models.IntegerField(default=0)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Members')),
            ],
        ),
        migrations.CreateModel(
            name='TotalCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r10000', models.IntegerField(default=0)),
                ('r5000', models.IntegerField(default=0)),
                ('r2000', models.IntegerField(default=0)),
                ('r1000', models.IntegerField(default=0)),
                ('r500', models.IntegerField(default=0)),
                ('r100', models.IntegerField(default=0)),
                ('r50', models.IntegerField(default=0)),
            ],
        ),
    ]
