# Generated by Django 3.0.5 on 2020-05-10 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Members')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Table')),
            ],
        ),
    ]
