# Generated by Django 3.0.5 on 2020-05-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200510_1928'),
        ('member', '0002_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='menu.Table'),
        ),
    ]
