# Generated by Django 3.0.5 on 2020-05-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200508_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='menu.Category'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(default='vacant', max_length=20),
        ),
    ]
