# Generated by Django 3.0.5 on 2020-05-12 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200510_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotitem',
            name='category_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
